"""Initialize

Revision ID: 289869099d4b
Revises:
Create Date: 2024-03-16 20:48:10.947353

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "289869099d4b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mark_to_delete", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_path", sa.String(), nullable=True),
        sa.Column("image_delete_url", sa.String(), nullable=True),
        sa.Column("longitude", sa.Double(), nullable=False),
        sa.Column("latitude", sa.Double(), nullable=False),
        sa.Column("create_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("update_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("latitude >= -90 and latitude <= 90 ", name=op.f("ck_entries_check_latitude")),
        sa.CheckConstraint("longitude >= -180 and longitude <= 180 ", name=op.f("ck_entries_check_longitude")),
        sa.CheckConstraint("update_date >= create_date ", name=op.f("ck_entries_check_update_time")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entries")),
    )
    op.create_index("ix_entries_coordinates", "entries", ["longitude", "latitude"], unique=False)
    op.create_index(op.f("ix_entries_user_id"), "entries", ["user_id"], unique=False)
    op.create_table(
        "hidden_entries",
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["entries.id"], name=op.f("fk_hidden_entries_entry_id_entries"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("entry_id", "user_id", name=op.f("pk_hidden_entries")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hidden_entries")
    op.drop_index(op.f("ix_entries_user_id"), table_name="entries")
    op.drop_index("ix_entries_coordinates", table_name="entries")
    op.drop_table("entries")
    # ### end Alembic commands ###
