"""Add: remove mark_to_delete flag

Revision ID: 4ce2a1b9703d
Revises: 320273528fb2
Create Date: 2024-07-07 18:54:14.652658

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ce2a1b9703d"
down_revision: Union[str, None] = "320273528fb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entries", "mark_to_delete")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entries", sa.Column("mark_to_delete", sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
