"""Add: create_date and update_date to hidden_entries

Revision ID: 8234f673b3d3
Revises: 4ce2a1b9703d
Create Date: 2024-07-08 21:10:13.578344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8234f673b3d3"
down_revision: Union[str, None] = "4ce2a1b9703d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hidden_entries",
        sa.Column("create_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column(
        "hidden_entries",
        sa.Column("update_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hidden_entries", "update_date")
    op.drop_column("hidden_entries", "create_date")
    # ### end Alembic commands ###
